//
//  DetailProductProtocols.swift
//  NTTDATA
//
//  Created Luis Fernando Flores Rivera on 31/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailProductWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol DetailProductPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol DetailProductInteractorProtocol: AnyObject {

  var presenter: DetailProductPresenterProtocol?  { get set }
}

//MARK: View -
protocol DetailProductViewProtocol: AnyObject {

  var presenter: DetailProductPresenterProtocol?  { get set }
}
