//
//  DetailProductPresenter.swift
//  NTTDATA
//
//  Created Luis Fernando Flores Rivera on 31/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductPresenter {
    //MARK: - Protocol Properties
    weak private var view: DetailProductViewProtocol?
    var interactor: DetailProductInteractorProtocol?
    private let router: DetailProductWireframeProtocol

    //MARK: - Life Cycle
    init(interface: DetailProductViewProtocol, interactor: DetailProductInteractorProtocol?, router: DetailProductWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension DetailProductPresenter: DetailProductPresenterProtocol {
    
}

//MARK: - Private functions
extension DetailProductPresenter {
    
}
