//
//  DetailProductInteractor.swift
//  NTTDATA
//
//  Created Luis Fernando Flores Rivera on 31/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductInteractor {
    //MARK: - Protocol Properties
    weak var presenter: DetailProductPresenterProtocol?
}

//MARK: - Interactor Methods
extension DetailProductInteractor: DetailProductInteractorProtocol {
    
}
