//
//  DetailProductRouter.swift
//  NTTDATA
//
//  Created Luis Fernando Flores Rivera on 31/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductRouter {
    //MARK: - Protocol Properties
    weak var viewController: UIViewController?
    
    //MARK: - Static Methods
    static func createModule(data: Product) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DetailProductViewController(nibName: nil, bundle: nil)
        let interactor = DetailProductInteractor()
        let router = DetailProductRouter()
        let presenter = DetailProductPresenter(interface: view, interactor: interactor, router: router)
        view.data = data
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
       
        
        return view
    }
}

//MARK: - Router Metods
extension DetailProductRouter: DetailProductWireframeProtocol {
    
}

//MARK: - Private functions
extension DetailProductRouter {
    
}
