//
//  HomeProtocols.swift
//  NTTDATA
//
//  Created Luis Fernando Flores Rivera on 31/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {
    func nextView(info: Product)
}
//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject {
    func getInitData()
    func dataSource(data: dataInfo)
    func nextView(info: Product)

}

//MARK: Interactor -
protocol HomeInteractorProtocol: AnyObject {
    func getInitData()
  var presenter: HomePresenterProtocol?  { get set }
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {
    func dataSource(data: dataInfo)

  var presenter: HomePresenterProtocol?  { get set }
}
